<?php

namespace Shah\Novus\Services\AI;

/**
 * Service to generate specialized prompts for article editing
 */
class PromptService
{
    /**
     * Generate a prompt to improve writing quality
     */
    public function improve(string $selectedText): string
    {
        return <<<EOT
You are a professional editor helping improve article content. Enhance the following text to be more engaging,
clear, and professional.

Make sure your revision:
- Maintains the original message and tone
- Improves grammar, word choice, and flow
- Reads like it was written by a skilled human writer, not AI
- Avoids generic phrasing and robotic-sounding sentences
- Includes natural language variations and conversational elements
- Uses contractions where appropriate and varies sentence structure
- Keeps approximately the same length
- Doesn't use obvious AI phrases like "I'd be happy to help" or "As an AI"

FORMAT YOUR RESPONSE AS PROPER MARKDOWN. Use appropriate Markdown formatting for headings, lists, emphasis,
links, and other elements as needed. Do not include markdown code blocks or any explanation about the formatting.
Just provide the well-formatted Markdown content directly.

Here's the text to improve:

{$selectedText}
EOT;
    }

    /**
     * Generate a prompt to make text shorter/more concise
     */
    public function shorten(string $selectedText, ?int $targetLength = null): string
    {
        $lengthInstruction = $targetLength ? "Aim for approximately {$targetLength} words." : 'Make it about 40-50% shorter.';

        return <<<EOT
You are a skilled editor who specializes in condensing text. Make the following text more concise while preserving
all key points, main arguments, and essential information. {$lengthInstruction}

Your shortened version must:
- Sound completely natural and human-written
- Avoid the formal, rigid structure common in AI writing
- Have a conversational and authentic tone
- Use varied sentence structures and natural transitions
- Never use AI phrases like "In summary" or "In conclusion"
- Preserve the human voice and personality of the original
- Have authentic imperfections that make writing feel human
- Flow naturally without sounding compressed or robotic

FORMAT YOUR RESPONSE AS PROPER MARKDOWN. Use appropriate Markdown formatting for headings, lists, emphasis,
links, and other elements as needed. Do not include markdown code blocks or any explanation about the formatting.
Just provide the well-formatted Markdown content directly.

Here's the text to shorten:

{$selectedText}
EOT;
    }

    /**
     * Generate a prompt to expand text with more details and content
     */
    public function expand(string $selectedText, ?int $targetLength = null): string
    {
        $lengthInstruction = $targetLength ? "Aim for approximately {$targetLength} words." : 'Make it about twice as long.';

        return <<<EOT
You are a professional writer who excels at elaborating on ideas. Expand the following text with additional relevant details,
examples, context, and supporting points. {$lengthInstruction}

When expanding the text:
- Write in a distinctly human style with natural imperfections
- Incorporate conversational elements like occasional asides or questions
- Use a mix of complex and simple sentences at irregular intervals
- Include slight detours and tangential thoughts as humans naturally do
- Avoid the robotic organization and perfect structure of AI writing
- Never use AI introductory phrases or formulaic transitions
- Add personality and unique perspectives that feel authentic
- Make it impossible to tell this was expanded by AI

FORMAT YOUR RESPONSE AS PROPER MARKDOWN. Use appropriate Markdown formatting for headings, lists, emphasis,
links, and other elements as needed. Do not include markdown code blocks or any explanation about the formatting.
Just provide the well-formatted Markdown content directly.

Here's the text to expand:

{$selectedText}
EOT;
    }

    /**
     * Generate a prompt to adjust the tone of the text
     */
    public function adjustTone(string $selectedText, string $targetTone): string
    {
        return <<<EOT
You are an expert editor. Rewrite the following text to adjust its tone to be more {$targetTone},
while preserving the original meaning and key points.

Your rewritten version must:
- Sound authentically human with natural language patterns
- Avoid perfect grammar or overly consistent structure
- Include minor imperfections that make human writing distinctive
- Use conversational elements appropriate to the {$targetTone} tone
- Never sound like it was generated by AI
- Maintain the human voice and personality throughout
- Keep a natural flow and casual language where appropriate
- Avoid academic or formal constructions unless specifically requested

FORMAT YOUR RESPONSE AS PROPER MARKDOWN. Use appropriate Markdown formatting for headings, lists, emphasis,
links, and other elements as needed. Do not include markdown code blocks or any explanation about the formatting.
Just provide the well-formatted Markdown content directly.

Here's the text to rewrite:

{$selectedText}
EOT;
    }

    /**
     * Generate a prompt for SEO metadata generation
     */
    public function generateSeo(string $title, string $excerpt): string
    {

        return <<<EOT
You are an expert SEO analyst with deep knowledge of search engine optimization. Generate comprehensive SEO metadata
for the following blog post or article content.

Based on the provided information, create optimized SEO metadata that:
- Captures the essence of the content in a compelling way
- Uses relevant keywords naturally without keyword stuffing
- Follows SEO best practices for title and description length
- Creates engaging preview text for social media platforms
- Maintains a professional yet enticing tone that encourages clicks

Provide your response as a JSON object with these exact fields:
- meta_title (50-60 characters max)
- meta_description (150-160 characters max)
- meta_keywords (comma-separated relevant keywords, 5-8 terms)
- og_title (Open Graph title, 60-70 characters max)
- og_description (Open Graph description, 150-200 characters max)
- twitter_title (55-70 characters max)
- twitter_description (150-200 characters max)

Here's the content to analyze:

TITLE: {$title}

EXCERPT: {$excerpt}


ONLY RETURN A VALID JSON OBJECT WITH THE FIELDS LISTED ABOVE. NO INTRODUCTION, EXPLANATION OR OTHER TEXT.
EOT;
    }
}
