name: Code Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Check PHP code formatting
        run: vendor/bin/pint --test
        
      - name: Show PHP formatting summary
        run: |
          echo "## PHP Code Formatting Check Complete :art:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Tool: Laravel Pint" >> $GITHUB_STEP_SUMMARY
          echo "- Mode: Check only (no modifications)" >> $GITHUB_STEP_SUMMARY
        
  format-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci

      - name: Setup CI environment (if needed)
        run: |
          chmod +x ./.github/workflows/setup-ci.sh
          ./.github/workflows/setup-ci.sh
      
      - name: Check JavaScript/TypeScript code formatting
        run: npm run format:check
        
      - name: Show JS formatting summary
        run: |
          echo "## JavaScript/TypeScript Code Formatting Check Complete :art:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Tool: Prettier" >> $GITHUB_STEP_SUMMARY
          echo "- Command: \`npm run format:check\`" >> $GITHUB_STEP_SUMMARY
          echo "- Mode: Check only (no modifications)" >> $GITHUB_STEP_SUMMARY