name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formatting:
    name: Code Formatting
    uses: ./.github/workflows/code-formatting.yml

  php-tests:
    name: PHP Tests
    needs: formatting
    uses: ./.github/workflows/php-tests.yml

  js-tests:
    name: JavaScript Tests
    needs: formatting
    uses: ./.github/workflows/js-tests.yml

  build:
    name: Build Project
    needs: [php-tests, js-tests]
    uses: ./.github/workflows/build.yml